version: '3'
services:
  capture-traffic:
    build: .
    network_mode: "host"
    depends_on:
      - db
    ports:
      - "5000:5000"

  db:
    image: postgres
    restart: always
    network_mode: "host"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    network_mode: "host"
    ports:
      - "8080:8080"
    depends_on:
      - db
      - capture-traffic

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  postgres-data:
    driver: local
