services:
  db:
    container_name: meli-db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -d my_database -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    container_name: meli-frontend
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

  backend:
    container_name: meli-backend
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  microservice:
    container_name: meli-traffic
    build: ./
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
