version: '3'
services:
  backend:
    build: ./backend # Path to your backend Dockerfile
    network_mode: "host"
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - NODE_ENV=production # Set environment variables as needed
      - PGHOST=db # Use the service name defined in Docker Compose for host resolution
      - PGDATABASE=my_database
      - PGUSER=postgres
      - PGPASSWORD=mysecretpassword
  capture-traffic:
    build: .
    network_mode: "host"
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  postgres-data:
    driver: local
